### ISSUE TITLE
Unable to run same code in my app

### ISSUE THREAD

**Issue by nitish52** [yhirano/MyAdobeCreativeSdkImageEditingSample#1]
Hi, your sample editing is working fine. but when i implement same class in my app then it is showing error:-
 Your Application must implements IAviaryClientCredentials.
 i create secret key and client id for my app. and i also change android:authority  for my provider.
can you help me??

**Comment by yhirano** [comment]
Please check your AndroidManifest.xml.
Maybe, it necessary to specify the full path to the name of the Application class.

**Comment by nitish52** [comment]
thanks, i solved my problem.
