### ISSUE TITLE
'AdobeCreativeSDKFoundation/AdobeCreativeSDKFoundation.h' file not found

### ISSUE THREAD

**Issue by sultan-arshi** [yhirano/MyAdobeCreativeSdkImageEditingSample#2]
i downloaded the sample and tried to compile but all the sdk files are not there
i also downloaded the AdobeCretiveSdk but it do no have AdobeCreativeSDKFoundation.bundle or frame work
can you please help me

**Comment by yhirano** [comment]
This sample is obsolete.
You probably can built it with Creative SDK v0.10.2096, but can't built with the latest SDK (Creative SDK v0.15.2181.1).
You had better see Adobe's SDK sample instead of my sample.
